#!/bin/sh
  
set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet disable openarc.service

  if test -f "disabled.bin"; then
    echo "arc is already disabled."
  else
    touch "disabled.bin"
    if systemctl is-active --quiet openarc-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl stop openarc.service
    else
      echo "arc will be disabled on next reboot."
    fi
  fi

fi


