#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet enable openarc.service

  if test ! -f "disabled.bin"; then
    echo "arc is already enabled."
  else
    rm "disabled.bin"
    mkdir -p /etc/device/services/mail/smtp/milters
    ln -s -f /run/openarc/openarc.sock /etc/device/services/mail/smtp/milters/20-openarc
    if systemctl is-active --quiet openarc-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl restart openarc-autodiscovery.service
      /usr/bin/sudo /usr/bin/systemctl restart openarc.service
    else
      echo "arc will be enabled on next reboot."
    fi
  fi

fi

