#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet enable openarc.service

  if test ! -f "disabled.bin"; then
    echo "arc is already enabled."
  elif test ! -f "/etc/device/services/mail/smtp/arc/domain.txt"; then
    echo "domain is required to enable arc"
  elif test ! -L "/etc/device/services/mail/smtp/arc/key.pem"; then
    echo "key is required to enable arc"
  else
    rm "disabled.bin"
    if systemctl is-active --quiet openarc-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl restart openarc-autodiscovery.service
      /usr/bin/sudo /usr/bin/systemctl restart openarc.service
    else
      echo "arc will be enabled on next reboot."
    fi
  fi

fi

