#!/bin/sh

set -e
umask 0002

OPTIONS="--polar disabled --hostname selector --required --fqdn domain --symlink-base=/etc/pki/tls/private --symlink-suffix=.pem --symlink=key"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  if test -f "disabled.bin"; then
    /usr/bin/sudo /usr/bin/systemctl --quiet disable openarc.service
    if systemctl is-active --quiet openarc-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl stop openarc.service
    else
      echo "arc will be disabled on next reboot."
    fi
  else
    /usr/bin/sudo /usr/bin/systemctl --quiet enable openarc.service
    if systemctl is-active --quiet openarc-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl restart openarc-autodiscovery.service
      /usr/bin/sudo /usr/bin/systemctl restart openarc.service
    else
      echo "arc will be enabled on next reboot."
    fi
  fi

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

